### ISSUE TITLE
iCloud service unavailable (503?)

### ISSUE THREAD

**Issue by boozook** [gongzhang/HiCoffeeApp#14]
Reset cloud sync state don't solves the problem.

<image src="https://user-images.githubusercontent.com/888526/150678453-abec97ea-1af2-4bac-bb73-1238a8986dc3.png" width="260" />

<image src="https://user-images.githubusercontent.com/888526/150678509-7c1565b3-7171-45e7-90e7-1992cd40bdc6.png" width="260" />

**Comment by gongzhang** [comment]
This Apple iCloud issue has been troubling me for three months now. But rest assured, I haven't given up yet. Maybe an alternate sync service option will be added.

https://github.com/gongzhang/awesome-icloud-503

**Comment by gongzhang** [comment]
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/4470629/151083466-48b6be59-6492-40d1-85a4-26b83d97cdf7.png">

@fzzr- 👋 I'm glad Apple is starting to respond to this issue. This is a message from the Apple Developer forum an hour ago. Please help to confirm if they really fixed the iCloud issue. Thanks!

**Comment by boozook** [comment]
The problem is gone, the issue can be closed. Thanks! 🎉
