### ISSUE TITLE
Metabolic parameters don’t accept more than 800mg caffeine

### ISSUE THREAD

**Issue by cookingwithrye** [gongzhang/HiCoffeeApp#18]
And it silently strips off last digit e.g. put in “1200” and it got turned into “120”

![A5A102D8-A9AF-4D61-B6FF-D15DEDAFE466](https://user-images.githubusercontent.com/2432689/178107696-de01b043-c171-4427-84e1-3183dad1b598.jpeg)
![4DC21EC8-2485-4080-BBD0-601C9C8E7EF4](https://user-images.githubusercontent.com/2432689/178107697-5b42a168-aefd-4cea-8171-5f12d875036f.jpeg)
![5D238E02-8454-4795-A463-3F2619065485](https://user-images.githubusercontent.com/2432689/178107700-6a46fb38-ee0b-4fa9-8b41-7631c4c6e70c.jpeg)

**Comment by gongzhang** [comment]
@cookingwithrye Thanks for reporting this! The next version will raise the limit first. 😄

**Comment by cookingwithrye** [comment]
> @cookingwithrye Thanks for reporting this! The next version will raise the limit first. 😄

Thanks, liking your app as I try to track and cut down on caffeine in a busy time in my life. Just upgraded

I find these little focused tools make a big difference vs using a spreadsheet lol
