### ISSUE TITLE
Shortcuts asks for permissions every time

### ISSUE THREAD

**Issue by boozook** [gongzhang/HiCoffeeApp#21]
Every time when I run my simple shortcut, it asks me for permissions. Every bloody time.

Versions: all actual,
iOS & watchOS is latest public betas.
iOS: 16.0 (20A362)
watchOS: 9.0

Permission request: ![incoming-892CB69F-4267-4854-A805-25A173358D60](https://user-images.githubusercontent.com/888526/189519733-e4af049b-0613-49c6-875e-b298f442f8b6.PNG)

<details> 
  <summary>Shortcut:</summary>

![IMG_9706](https://user-images.githubusercontent.com/888526/189519729-61282a92-1ef5-42e8-998a-62f07ae717bd.PNG)

</details>

**Comment by gongzhang** [comment]
@boozook Thanks for the feedback! I will look into this issue.

**Comment by boozook** [comment]
All is fixed. Thanks! ❤️‍🔥
I haven't see this problem for a long time (some weeks).
I'm sure this issue can be closed.
