### ISSUE TITLE
HiCoffee的设备间iCloud同步有问题

### ISSUE THREAD

**Issue by EricYuan8307** [gongzhang/HiCoffeeApp#32]
HiCoffee中，在不同设备间记录的咖啡数据无法立刻同步。
在ipad上记录之后，只要我不打开iphone和mac的app，数据就永远无法同步。必须要打开app等待同步才行。即使我对所有设备都打开了后台刷新，依旧需要打开app才能操作。照理来说，其他app都能在后台自动刷新同步数据，为什么HiCoffee不行呢？
不仅是咖啡数据，连高级会员的同步也出现了问题。高级会员也需要在不同设备上重新订阅才行，没法自动同步。
应该是HiCoffee上iCloud同步的问题，请尽快解决，否则真的很影响使用。

**Comment by gongzhang** [comment]
感谢反馈，预期应该是能够在后台自动同步的。我自己也注意到这个问题，会专门解决一下。
