### ISSUE TITLE
Health - Sleep time

### ISSUE THREAD

**Issue by jeremieb** [gongzhang/HiCoffeeApp#35]
Hey man! I cannot authorize the app for reading the sleep time. The sheet doesn't open. 

No problem with the heart beat though.
Thanks for this amazing app!

Jeremie

**Comment by gongzhang** [comment]
Hi @jeremieb ,

Regarding the issue you're facing, could you please confirm if you still see the "Authorize Health Data..." button on the Charts tab? And if so, does nothing happen when you tap on it?

Best regards,
Gong

**Comment by jeremieb** [comment]
Yes I can, but tapping on it doesn't trigger the authorization sheet like it did for the heart beat. 

![image](https://github.com/gongzhang/HiCoffeeApp/assets/736246/250595f0-919d-4bf4-8f34-02f3a5ed0547)

**Comment by jeremieb** [comment]
I'm on an iPhone 15 Pro under 17.1 (production release), forgot that part sorry.

**Comment by gongzhang** [comment]
👍 Thanks! @jeremieb The bug will be fixed in tomorrow's update. Before that, could you try the button on the root page?

<img width="300px" src="https://github.com/gongzhang/HiCoffeeApp/assets/4470629/bfe5bcb2-d8e1-4ba3-838f-78566b89d333"></img>

**Comment by jeremieb** [comment]
Sorry didn't see your message. It's fixed with the update. Thanks man! ☺️
