### ISSUE TITLE
Broken Shortcuts integration

### ISSUE THREAD

**Issue by boozook** [gongzhang/HiCoffeeApp#9]
![image](https://user-images.githubusercontent.com/888526/136470142-0adbccee-da38-405e-b8e3-f316c8052866.png)

[reproduction screencast](https://user-images.githubusercontent.com/888526/136470182-2fe00678-bd61-4f3c-9b85-1b0340961401.MOV)

**Comment by boozook** [comment]
Also Watches requests permission to null **every time** I run it.
![image](https://user-images.githubusercontent.com/888526/136551711-bb3d8fd5-c75e-4a2f-887c-5a61e43921f4.png)

**Comment by gongzhang** [comment]
@fzzr- 🤔 Yes, something is broken. I'm trying to fix it.

**Comment by gongzhang** [comment]
- https://forums.macrumors.com/threads/shortcuts-to-web-open-in-chrome-bug.2312693/
- https://stackoverflow.com/questions/69292113/weird-shortcuts-problem-on-ios-15-and-watchos-8
- https://discussions.apple.com/thread/253161866
- https://community.openhab.org/t/shortcuts-defined-with-ios-15-using-openhab-dont-work-correct-on-applewatch/126737
- https://forums.macrumors.com/threads/apple-watch-shortcut-asking-allow-to-share-data.2314340/
- https://gotailwind.zendesk.com/hc/en-us/community/posts/4410053748621-Using-apple-shortcuts-on-watch

**Comment by gongzhang** [comment]
@fzzr- I'm still trying to fix the problem. If you recreate the same shortcut, will it still have the problem?

**Comment by boozook** [comment]
Still same error. 
Maybe I can get some logs from device for you. 🧐 Do you know how to do it?

**Comment by gongzhang** [comment]
@fzzr- 🤔 I was able to reproduce the problem in a simulator here, but didn't use it to get useful information. It seems to be an iOS issue. You can try the following operation.

In the Shortcuts app, edit an shortcut, then you can go to settings in the upper right corner and see a "privacy" tab. You can try Reset Privacy and then turn it back on.

https://discussions.apple.com/thread/253161866?answerId=256217910022

> This is because of a new added feature in iOS 15 to protect access to data by shortcuts. If you go to Shortcuts, go into editing mode, then open the settings in the upper right, you will see the new Privacy tab. Once you grant access the first time, you should see the app or other data location listed with the slide switch On. You ‘could’ toggle it to Off but then your shortcut most likely would not function correctly. If you select Reset Privacy, it will clear the saved info. The next time you run the shortcut, the privacy prompt will reoccur. On the positive side, it looks like privacy items are automatically added as On when creating new shortcuts within the Shortcut app.

**Comment by boozook** [comment]
I haven't been used it for a while because of this issue. Well, now I see this is fixed completely. ❤️‍🔥
Thank you so much! It works almost perfectly!

Almost because now I have new issue for you #21.
Every time when I run my simple shortcut it always asks for permissions. Every time.

![incoming-892CB69F-4267-4854-A805-25A173358D60](https://user-images.githubusercontent.com/888526/189519733-e4af049b-0613-49c6-875e-b298f442f8b6.PNG)

**Comment by boozook** [comment]
All is fixed. Thanks! ❤️‍🔥
